name: NationsAndRanks
main: net.skwh.NationsAndRanks.Core
version: 0.5
commands:
  NAR:
    description: Offers information about the plugin.
    permission: NationsAndRanks.Info
  SetRank:
    description: Sets the Rank of a Player.
    aliases: [sr,SetRank]
    permission: NationsAndRanks.SetRank
    usage: "Usage: /<command> [player] [rank]"
    permission-message: You do not have access to this command!
  SetVerbose:
    description: Sets the length of descriptors for players.
    aliases: [sv,SetVerbose]
    permission: NationsAndRanks.SetVerbose
    usage: "Usage: /<command> [true/false]"
    permission-message: You do not have access to this command!
  JoinNation:
    description: The sender becomes a citizen of the given nation.
    aliases: [jn,join,JoinNation]
    permission: NationsAndRanks.JoinNation
    usage: "Usage: /<command> [nation]"
    permission-message: You do not have access to this command!
  JoinGuild:
    description: The sender becomes a member of the given guild.
    aliases: [jg,JoinGuild]
    permission: NationsAndRanks.JoinGuild
    usage: "Usage: /<command> [guild]"
    permission-message: You do not have access to this command!
permissions:
  NationsAndRanks.*:
    description: Gives access to all Nations and Ranks commands.
    default: op
    children:
      NationsAndRanks.Info: true
      NationsAndRanks.SetRank: true
      NationsAndRanks.SetVerbose: true
      NationsAndRanks.JoinNation: true
      NationsAndRanks.JoinGuild: true
  NationsAndRanks.Info:
    description: Gives access to the nar command.
    default: true
  NationsAndRanks.SetRank:
    description: Gives access to the SetRank command.
    default: true
  NationsAndRanks.SetVerbose:
    description: Gives access to the SetVerbose command.
    default: op
  NationsAndRanks.JoinNation:
    description: Gives access to the JoinNation command.
    default: true
  NationsAndRanks.JoinGuild:
    description: Gives access to the JoinGuild command.
    default: true