name: NationsAndRanks
main: net.skwh.NationsAndRanks.Core
version: 0.8
commands:
  NAR:
    description: Offers information about the plugin.
    permission: NationsAndRanks.Info
  SetRank:
    description: Sets the Rank of a Player.
    aliases: [sr,SetRank]
    permission: NationsAndRanks.SetRank
    usage: "Usage: /<command> [player] [rank]"
    permission-message: You do not have access to this command!
  JoinNation:
    description: The sender becomes a citizen of the given nation.
    aliases: [jn,JoinNation]
    permission: NationsAndRanks.JoinNation
    usage: "Usage: /<command> [nation]"
    permission-message: You do not have access to this command!
  JoinGuild:
    description: The sender becomes a member of the given guild.
    aliases: [jg,JoinGuild]
    permission: NationsAndRanks.JoinGuild
    usage: "Usage: /<command> [guild]"
    permission-message: You do not have access to this command!
  List:
    description: Lists Guilds/Ranks/Nations based on the argument given.
    permission: NationsAndRanks.List
    usage: "Usage: /<command> [ranks/guilds/nations]"
    permission-message: You do not have access to this command!
  SetGuildSpawn:
    description: Sets the spawn of a given guild to the sender's current location.
    aliases: [sgs]
    permission: NationsAndRanks.SetGuildSpawn
    usage: "Usage: /<command> [guild]"
    permission-message: You do not have access to this command!
  GetRank:
    description: returns the Guild and rank of the sender, if any.
    aliases: [gr]
    permission: NationsAndRanks.GetRank
    usage: "Usage: /<command>"
    permission-message: You do not have access to this command!
permissions:
  NationsAndRanks.*:
    description: Gives access to all Nations and Ranks commands.
    default: op
    children:
      NationsAndRanks.Info: true
      NationsAndRanks.SetRank: true
      NationsAndRanks.JoinNation: true
      NationsAndRanks.JoinGuild: true
      NationsAndRanks.List: true
      NationsAndRanks.SetGuildSpawn: true
      NationsAndRanks.GetRank: true
  NationsAndRanks.Info:
    description: Gives access to the nar command.
    default: true
  NationsAndRanks.SetRank:
    description: Gives access to the SetRank command.
    default: op
  NationsAndRanks.JoinNation:
    description: Gives access to the JoinNation command.
    default: true
  NationsAndRanks.JoinGuild:
    description: Gives access to the JoinGuild command.
    default: true
  NationsAndRanks.List:
    description: Gives access to the List command.
    default: true
  NationsAndRanks.SetGuildSpawn:
    description: Gives access to the SetGuildSpawn command.
    default: op
  NationsAndRanks.GetRank:
    description: Gives access to the GetRank command.
    default: true