name: NationsAndRanks
main: net.skwh.NationsAndRanks.Core
version: 0.5
commands:
  NAR:
    description: Offers information about the plugin.
    permission: NationsAndRanks.Info
  SetRank:
    description: Sets the Rank of a Player.
    aliases: [sr,SetRank]
    permission: NationsAndRanks.SetRank
    usage: "Usage: /<command> [player] [rank]"
    permission-message: You do not have access to this command!
  SetBorders:
    description: Sets the Borders for a Nation.
    aliases: [sb, SetBorders]
    permission: NationsAndRanks.SetBorders
    usage: "Usage: /<command> [borders]"
    permission-message: You do not have access to this command!
  SetColor:
    description: Sets the text color for a Nation. Use color names like blue, yellow, red to set the color.
    aliases: [sc, SetColor, SetColour]
    permission: NationsAndRanks.SetColor
    usage: "Usage: /<command> [color]"
    permission-message: You do not have access to this command!
  SetVerbose:
    description: Sets the length of descriptors for players.
    aliases: [sv,SetVerbose]
    permission: NationsAndRanks.SetVerbose;
    usage: "Usage: /<command> [true/false]"
    permission-message: You do not have access to this command!
  JoinNation:
    description: The sender becomes a citizen of the given nation.
    aliases: [jn,join,JoinNation]
    permission: NationsAndRanks.JoinNation;
    usage: "Usage: /<command> [nation]"
    permission-message: You do not have access to this command! 
permissions:
  NationsAndRanks.*:
    description: Gives access to all Nations and Ranks commands.
    default: op
    children:
      NationsAndRanks.Info: true
      NationsAndRanks.SetRank: true
      NationsAndRanks.SetBorders: true
      NationsAndRanks.SetColor: true
      NationsAndRanks.SetVerbose: true
      NationsAndRanks.JoinNation: true
  NationsAndRanks.Info:
    description: Gives access to the nar command.
    default: true
  NationsAndRanks.SetRank:
    description: Gives access to the SetRank command.
    default: true
  NationsAndRanks.SetBorders:
    description: Gives access to the SetBorders command.
    default: true
  NationsAndRanks.SetColor:
    description: Gives access to the SetColor command. 
    default: true
  NationsAndRanks.SetVerbose:
    description: Gives access to the SetVerbose command.
    default: op
  NationsAndRanks.JoinNation:
    description: Gives access to the JoinNation command.
    default: true